In [24]:
import torch

## Sigmoid Activation Function 

In [25]:
def activation(x):
    return 1 / (1 + torch.exp(-x))

## Generate Some Data

In [26]:
torch.manual_seed(7)  #generated random number will not change over time (generate same random data every time)

#generate 5 random normalized variable Normal =(mean = 0, standard deviation = 1)
features = torch.randn((1, 5))

# true weights for our data  (create a tensor with the same shape as feature)
weights = torch.randn_like(features) # equavalent to torch.randn(features.size(), dtype=features.dtype, layout=features.layout)

#true bias term
bias = torch.randn((1, 1))

## Calculate The Output of The Tensor Using Weights and Bias Term

Above I generated data we can use to get the output of our simple network. This is all just random for now, going forward we'll start using normal data. Going through each relevant line:

features = torch.randn((1, 5)) creates a tensor with shape (1, 5), one row and five columns, that contains values randomly distributed according to the normal distribution with a mean of zero and standard deviation of one.

weights = torch.randn_like(features) creates another tensor with the same shape as features, again containing values from a normal distribution.

Finally, bias = torch.randn((1, 1)) creates a single value from a normal distribution.

PyTorch tensors can be added, multiplied, subtracted, etc, just like Numpy arrays. In general, you'll use PyTorch tensors pretty much the same way you'd use Numpy arrays. They come with some nice benefits though such as GPU acceleration which we'll get to later. For now, use the generated data to calculate the output of this simple single layer network.

In [28]:
y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)

## Calculate the output of neural network using matrix multiplication

As you're building neural networks in any framework, you'll see this often. Really often. What's happening here is our tensors aren't the correct shapes to perform a matrix multiplication. Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second column. Both features and weights have the same shape, (1, 5). This means we need to change the shape of weights to get the matrix multiplication to work.

Note: To see the shape of a tensor called tensor, use tensor.shape. If you're building neural networks, you'll be using this method often.

There are a few options here: weights.reshape(), weights.resize_(), and weights.view().

weights.reshape(a, b) will return a new tensor with the same data as weights with size (a, b) sometimes, and sometimes a clone, as in it copies the data to another part of memory.
weights.resize_(a, b) returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory). If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory. Here I should note that the underscore at the end of the method denotes that this method is performed in-place. Here is a great forum thread to read more about in-place operations in PyTorch.
weights.view(a, b) will return a new tensor with the same data as weights with size (a, b).
I usually use .view(), but any of the three methods will work for this. So, now we can reshape weights to have five rows and one column with something like weights.view(5, 1).

In [31]:
y = activation(torch.mm(features, weights.view(5, 1)) + bias)

## Multilayer Neural Network

In [33]:
# generate some data
torch.manual_seed(7)

# features are 3 normal random variable
features = torch.randn((1, 3))

# define the size of each layer in your network
n_inputes = features.shape[1] #input unit must match with features
n_hidden  = 2               # number of hidden unites
n_output = 1                # number of output unit

# weights from input to hidden layer
w1 = torch.randn(n_inputes, n_hidden)

# weights for hidden layer to output layer
w2 = torch.randn(n_hidden, n_output)

# and bias term for hidden and output layer
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


## Calculate the output of this multilayer network using weights w1 and w2 and bias b1, b2

In [34]:
h = activation(torch.mm(features, w1) + B1)
output = activation(torch.mm(h, w2) + B2)

In [35]:
print(output)

tensor([[0.3171]])


## Numpy to Toarch and Back

In [36]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.65529372, 0.50760148, 0.45577176],
       [0.84799796, 0.505962  , 0.35252291],
       [0.91285333, 0.27862753, 0.92708085],
       [0.53626496, 0.52543525, 0.28206489]])

In [37]:
b = torch.from_numpy(a)        # convert numpy to torch
b      

tensor([[0.6553, 0.5076, 0.4558],
        [0.8480, 0.5060, 0.3525],
        [0.9129, 0.2786, 0.9271],
        [0.5363, 0.5254, 0.2821]], dtype=torch.float64)

In [39]:
b.numpy()        # torch to numpy

array([[0.65529372, 0.50760148, 0.45577176],
       [0.84799796, 0.505962  , 0.35252291],
       [0.91285333, 0.27862753, 0.92708085],
       [0.53626496, 0.52543525, 0.28206489]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [40]:
b.mul(2)

tensor([[1.3106, 1.0152, 0.9115],
        [1.6960, 1.0119, 0.7050],
        [1.8257, 0.5573, 1.8542],
        [1.0725, 1.0509, 0.5641]], dtype=torch.float64)

In [41]:
a

array([[0.65529372, 0.50760148, 0.45577176],
       [0.84799796, 0.505962  , 0.35252291],
       [0.91285333, 0.27862753, 0.92708085],
       [0.53626496, 0.52543525, 0.28206489]])